// <auto-generated />
using ChefByStep.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChefByStep.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210616232108_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChefByStep.API.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "lemons",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "unsalted butter",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "prepared horseradish",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "kosher salt",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "shrimp",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "chopped dill",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "crusty bread",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "pasta\"",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "red onion",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Name = "salt",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Name = "cubed roasted chicken",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Name = "peppadews peppers",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 13,
                            Name = "marinated artichoke hearts",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 14,
                            Name = "smoked almonds",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 15,
                            Name = "thyme",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 16,
                            Name = "mustard",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 17,
                            Name = "sherry vinegar",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 18,
                            Name = "lemon",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 19,
                            Name = "olive oil",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 20,
                            Name = "black pepper",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 21,
                            Name = "garlic",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 22,
                            Name = "olives",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 23,
                            Name = "white fish",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 24,
                            Name = "salted capers",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 25,
                            Name = "white wine",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Name = "tomatoes",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 27,
                            Name = "linguine",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 28,
                            Name = "spaghetti",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 29,
                            Name = "parsley",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 30,
                            Name = "pepper",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 31,
                            Name = "oil",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 32,
                            Name = "sourdough bread",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 33,
                            Name = "cashews",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 34,
                            Name = "black mustard seeds",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 35,
                            Name = "urad dal",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 36,
                            Name = "asafetida",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 37,
                            Name = "shallot",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 38,
                            Name = "green chile",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 39,
                            Name = "fresh curry leaves",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 40,
                            Name = "ground turmeric",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 41,
                            Name = "cauliflower florets",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 42,
                            Name = "frozen peas",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 43,
                            Name = "plain full-fat yogurt",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 44,
                            Name = "cilantro",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 45,
                            Name = "fried egg",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 46,
                            Name = "key lime fillling",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 47,
                            Name = "key lime juice",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 48,
                            Name = "egg",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 49,
                            Name = "sweetened condensed milk",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 50,
                            Name = "coarse salt",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 51,
                            Name = "cornstarch",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 52,
                            Name = "cream cheese",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 53,
                            Name = "granulated sugar",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 54,
                            Name = "graham crackers",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 55,
                            Name = "neutral oil",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 56,
                            Name = "flour",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 57,
                            Name = "cake flour",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 58,
                            Name = "baking soda",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 59,
                            Name = "large eggs",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 60,
                            Name = "pure vanilla extract",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 61,
                            Name = "buttermilk",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = 62,
                            Name = "confectioners' sugar",
                            Quantity = 0.0
                        });
                });

            modelBuilder.Entity("ChefByStep.API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            CreatedById = 2,
                            Description = "A simple, scampi-inspired dinner that needs neither a lot of time, nor a lot of ingredients. The key is to swiftly simmer the shrimp and to rely on extrovert ingredients for seasoning. Lemon juice and lemon zest deliver loads of sunny acidity. So much so that we�re also using water, not stock, to stretch the brightness, and to ensure that there�s enough sauce for bread-sopping.",
                            ImageUrl = "https://images.food52.com/_51_B8XLkaL7wou2THrl1WXuadA=/1008x672/filters:format(webp)/3871c07e-9765-4a8d-9fdd-2f996094b105--2021-0518_speedy-shrimp_3x2_james-ransom-031.jpg",
                            Title = "Speedy Shrimp With Horseradish�Butter"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            CreatedById = 4,
                            Description = "If you like a good mayonnaise-based chicken salad, but one with more candid flavors, you should try this recipe! With a glass of white wine it would feel like the perfect weekend luch.",
                            ImageUrl = "https://images.food52.com/OOqBZEjQhcOLodgRlnXoOfVI5RY=/1008x672/filters:format(webp)/d8634211-6145-4329-81ca-711c45e4750a--2017-0427_chicken-salad_james-ransom-297.jpg",
                            Title = "Chicken Salad"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            CreatedById = 3,
                            Description = "Fish Pasta can be made with any flakey white fish. Snapper good but its best with fresh striped bass. Be very careful stirring the sauce: the fish should remain intact. The tomatoes should be fresh and cooked al crudo, till the juices are released but they are still a little raw. By adding the fish early on, its flavor infuses the whole sauce, so the tomatoes and fish are no longer separate entities, but fully integrated into the sauce. And the capers and olives reinforce the flavor of the fish with brine. It ends up being a more vibrant version of puttanesca. ",
                            ImageUrl = "https://images.food52.com/mlooIQOUxc3VtpQefZvmZiUY1Jw=/1008x672/filters:format(webp)/0afceb53-8c13-4b96-82ba-45235cf98176--fishpastalowres_2417.JPG",
                            Title = "Fish Pasta"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 0,
                            CreatedById = 2,
                            Description = "South Indian breakfast staple. Upma is a state of mind. The refrain is simple: Carb of choice, toasted in ghee-bloomed spices, then cooked with assorted vegetables and curry leaves and topped with tomato ketchup. In South India, the carb of choice is typically toasted semolina, thickened into a creamy, savory porridge. But it can also be made with bread. ",
                            ImageUrl = "https://images.food52.com/38ws8x4bhNB0a9zHq6ZSduhKXCY=/1008x672/filters:format(webp)/eb712a59-16c6-4f57-a6cf-8e523aa97e4e--2021-0312_bread-upma_3x2_mark-weinberg-193.jpg",
                            Title = "My Favorite Bread Upma "
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 0,
                            CreatedById = 2,
                            Description = "Key Lime Cake tastes like summer. Beachy. Floral. Have you ever rubbed your fingers across a wicker armrest and gotten lost in the undulating cords like waves?  ",
                            ImageUrl = "https://images.food52.com/NL2-zUmt3I_hFG3qnUfdKY6-bZQ=/1008x672/filters:format(webp)/7247d84f-cd2f-49ab-af78-4714ce5b0f92--Fruit_Cake_Key_Lime_Cake.jpg",
                            Title = "Key Lime Cake"
                        });
                });

            modelBuilder.Entity("ChefByStep.API.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.RecipeRating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeRatings");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMin = 0,
                            Instruction = "Finely grate the zest of 1 lemon and set aside. Now juice both lemons into a liquid measuring cup�you should get about 6 tablespoons. Add enough cold water to reach 1/2 cup of liquid total.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 2,
                            DurationMin = 0,
                            Instruction = "Melt 1� tablespoons of butter in a large skillet over medium heat. Stir in 1 tablespoon of horseradish, the lemon water, and a big pinch of salt. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 3,
                            DurationMin = 0,
                            Instruction = "As soon as that comes to a boil, add the shrimp and another big pinch of salt. Simmer for 2 to 4 minutes, flipping each shrimp halfway through, until pink and firm. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 4,
                            DurationMin = 0,
                            Instruction = "Stir in the remaining 1� tablespoons of butter and 1 tablespoon of horseradish. Taste and increase the horseradish, if you�d like. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 5,
                            DurationMin = 0,
                            Instruction = "Top with the lemon zest and dill, plus a sprinkle of salt (flaky is nice if you�ve got it), and serve with crusty bread for mopping up the sauce.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 6,
                            DurationMin = 0,
                            Instruction = "Sprinkle the onion with salt and toss to coat.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 7,
                            DurationMin = 0,
                            Instruction = " Let sit for 15 minutes.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 8,
                            DurationMin = 0,
                            Instruction = " Squeeze the onions to drain any juices. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 9,
                            DurationMin = 0,
                            Instruction = "In a bowl, toss together the onion, chicken, peppadews, artichoke hearts and almonds.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 10,
                            DurationMin = 0,
                            Instruction = " In a small bowl, whisk together the thyme, mustard and vinegar.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 11,
                            DurationMin = 0,
                            Instruction = " Gradually whisk in the oil.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 12,
                            DurationMin = 0,
                            Instruction = " Season with salt and pepper.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 13,
                            DurationMin = 0,
                            Instruction = " Pour the dressing over the chicken and fold together.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 14,
                            DurationMin = 0,
                            Instruction = " Squeeze in lemon juice.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 15,
                            DurationMin = 0,
                            Instruction = " Serve.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 16,
                            DurationMin = 0,
                            Instruction = "\"chop tomatoes roughly ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 17,
                            DurationMin = 0,
                            Instruction = "dice garlic ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 18,
                            DurationMin = 0,
                            Instruction = " deskin fish and cut into bite sized chunks ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 19,
                            DurationMin = 0,
                            Instruction = "saute three tablespoons of oil with garlic for two minutes or so over medium heat ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 20,
                            DurationMin = 0,
                            Instruction = "add fish, stirring carefully until browned. try not to break it up. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 21,
                            DurationMin = 0,
                            Instruction = "once browned, add salt and pepper, then half glass of white wine and turn up heat. stir carefully till wine is nearly evaporated. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 22,
                            DurationMin = 0,
                            Instruction = "meantime, heat pot of hot water for pasta, generously salted. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 23,
                            DurationMin = 0,
                            Instruction = "when wine is nearly evaporated, reduce heat, add tomatoes and cook for 10 minutes  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 24,
                            DurationMin = 0,
                            Instruction = " add capers, parsley and olives.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 25,
                            DurationMin = 0,
                            Instruction = "when the tomato juice is released and the sauce is just thickening, turn off heat.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 26,
                            DurationMin = 0,
                            Instruction = "cook pasta al dente. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 27,
                            DurationMin = 0,
                            Instruction = " carefully add the sauce to the pasta over a little heat.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 28,
                            DurationMin = 0,
                            Instruction = " stir gently for a minute or two  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 29,
                            DurationMin = 0,
                            Instruction = " serve.\"",
                            IsDone = false
                        },
                        new
                        {
                            Id = 30,
                            DurationMin = 0,
                            Instruction = "\"In a large skillet or wok set over medium-high heat, add 1 tablespoon of the ghee or oil and heat until shimmering.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 31,
                            DurationMin = 0,
                            Instruction = " Add the cubed bread and raw cashews to the pan and toast in oil until crunchy and golden brown, shaking the pan frequently and tossing the bread so it doesn�t burn. This will take 5 to 6 minutes.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 32,
                            DurationMin = 0,
                            Instruction = " Remove the toasted bread and cashews and set aside  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 33,
                            DurationMin = 0,
                            Instruction = " Lower the flame to medium and add the second tablespoon of cooking fat to the pan, heating until it�s shimmering.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 34,
                            DurationMin = 0,
                            Instruction = " Add the mustard seeds, urad dal, and asafetida and shake the pan vigorously to coat everything in the fat. In 20 to 30 seconds, the seeds will burst and the dal will become a deeply golden-brown color.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 35,
                            DurationMin = 0,
                            Instruction = " Add the onions, chile, salt, turmeric, and curry leaves and stir to combine   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 36,
                            DurationMin = 0,
                            Instruction = " raise the heat to medium-high and cook until the onions have softened and turned translucent, about 3 minutes.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 37,
                            DurationMin = 0,
                            Instruction = "  Add the cauliflower florets and stir, cooking for 3 to 5 minutes longer until they�ve softened and are completely coated with the spice and onion mixture.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 38,
                            DurationMin = 0,
                            Instruction = "Add the reserved bread and cashews to the pan with the vegetables and stir everything together, ensuring the onion mixture and cauliflower florets are evenly dispersed with the bread, cook together for about a minute more.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 39,
                            DurationMin = 0,
                            Instruction = " Add the peas and cook for another minute.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 40,
                            DurationMin = 0,
                            Instruction = " Carefully drizzle the yogurt over the upma and stir to combine so the bread and vegetables are completely coated",
                            IsDone = false
                        },
                        new
                        {
                            Id = 41,
                            DurationMin = 0,
                            Instruction = "  cook for 2 to 3 minutes more, stirring only occasionally, so the upma browns and crisps up some more, helped along with the lactose sugar in the yogurt.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 42,
                            DurationMin = 0,
                            Instruction = "Once the upma has crisped up to your desired texture, divide among bowls   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 43,
                            DurationMin = 0,
                            Instruction = " serve with chopped cilantro and a fried egg \"",
                            IsDone = false
                        },
                        new
                        {
                            Id = 44,
                            DurationMin = 0,
                            Instruction = "\"Key Lime Fillling ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 45,
                            DurationMin = 0,
                            Instruction = "Do yourself a favor and make the filling the night before you plan to assemble this cake. Have a fine-mesh sieve and a large bowl on standby near the stove.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 46,
                            DurationMin = 0,
                            Instruction = " Squeeze every last drop of juice from the limes and combine in a small saucepan with the yolks, condensed milk, salt, and cornstarch.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 47,
                            DurationMin = 0,
                            Instruction = " Whisk everything together until it�s nice and smooth and then set over medium heat. Don�t stop whisking.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 48,
                            DurationMin = 0,
                            Instruction = " Reduce the temperature a bit as the mixture thickens dramatically and keep whisking as it boils for 2 minutes, being especially careful to keep the edges of the pot from scorching.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 49,
                            DurationMin = 0,
                            Instruction = " Strain the mixture through the fine-mesh sieve into the bowl and stir gently with a rubber spatula to let off some of the steam.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 50,
                            DurationMin = 0,
                            Instruction = "  Add the cream cheese, one or two pieces at a time, and stir until all of it has been incorporated.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 51,
                            DurationMin = 0,
                            Instruction = " Place a piece of plastic film or wax paper directly on the surface of the custard to prevent a skin from forming and refrigerate until firm, at least 4 hours, preferably overnight.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 52,
                            DurationMin = 0,
                            Instruction = " Make the lime soaker by stirring the sugar into the juice until it�s dissolved. Set aside.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 53,
                            DurationMin = 0,
                            Instruction = " Use a serrated knife to trim the domes from the tops of the cakes and slice each in half horizontally to create four layers.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 54,
                            DurationMin = 0,
                            Instruction = " Place one layer on a serving platter and brush the top with about 2 tablespoons of the soaker.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 55,
                            DurationMin = 0,
                            Instruction = " Stir the lime filling briefly to loosen it, then use a small offset spatula to spread about one-third of the filling over the cake, getting it right up to the edge.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 56,
                            DurationMin = 0,
                            Instruction = "  Scatter a third of the graham cracker crumbs over the filling and top with another layer of cake.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 57,
                            DurationMin = 0,
                            Instruction = "  Continue assembling in this manner with the remaining filling and cake layers.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 58,
                            DurationMin = 0,
                            Instruction = " Slide a long wooden skewer vertically through the center of the cake if it feels wobbly.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 59,
                            DurationMin = 0,
                            Instruction = " Chill the assembled cake until you�re ready to make the meringue.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 60,
                            DurationMin = 0,
                            Instruction = " To make a Swiss meringue, place the egg whites and sugar in the heatproof bowl of an electric mixer.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 61,
                            DurationMin = 0,
                            Instruction = " Set the bowl over a pan of gently simmering water and heat, whisking occasionally, until the sugar is dissolved and the mixture reads 160�F (71�C) on a thermometer  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 62,
                            DurationMin = 0,
                            Instruction = "  Transfer the bowl to the mixer and whip on high speed until firm peaks form, about 5 minutes.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 63,
                            DurationMin = 0,
                            Instruction = " Remove the skewer from the chilled cake and dollop the meringue on top, piling it high.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 64,
                            DurationMin = 0,
                            Instruction = " Gently brown the meringue with a kitchen torch.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 65,
                            DurationMin = 0,
                            Instruction = " Serve at cool room temperature.   ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 66,
                            DurationMin = 0,
                            Instruction = " The cake can be stored, loosely covered, in the refrigerator for up to 2 days.  ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 67,
                            DurationMin = 0,
                            Instruction = " Pan Goo & Perfect Chiffon Cake Pan Goo In a small container with a lid, whisk the oil and flour together until combined. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 68,
                            DurationMin = 0,
                            Instruction = "Brush onto baking pans in place of parchment paper or cooking spray. Keep it in the fridge for a couple of weeks. Perfect Chiffon Cake Heat the oven to 350�F (180�C) and select your pans. For round layers, use two 8x2-inch round cake pans brushed with Pan Goo. For a roulade, use a 13x18-inch rimmed baking sheet lined with a silicone baking mat or parchment paper and brushed with Pan Goo. In a small bowl, whisk together the flour, salt, and baking soda. Set aside.In a large bowl, place the egg yolks and whisk in 1/2 cup of the granulated sugar, the vanilla, oil, and buttermilk. Set aside. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 69,
                            DurationMin = 0,
                            Instruction = "Using an electric mixer fitted with the whisk attachment, whip the egg whites on a healthy medium speed. When they look good and frothy, shake in the remaining 1/2 cup of the granulated sugar a little at a time, while slowly increasing the mixer speed to high. Keep whipping until the egg whites reach sturdy but not firm peaks.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 70,
                            DurationMin = 0,
                            Instruction = "Grab the dry ingredients and whisk them into the yolk mixture. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 71,
                            DurationMin = 0,
                            Instruction = "Make sure there are no lumps ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 72,
                            DurationMin = 0,
                            Instruction = "Then use a large rubber spatula to scoop about a third of the whipped egg whites into the batter and whisk to lighten the mixture. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 73,
                            DurationMin = 0,
                            Instruction = " Add the rest of the egg whites in two additions, folding gently until just combined.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 74,
                            DurationMin = 0,
                            Instruction = "Divide the batter evenly into the two prepared pans, filling each about halfway.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 75,
                            DurationMin = 0,
                            Instruction = "Bake until the cakes are golden brown and spring back excitedly when gently pressed and a cake tester inserted into the centers comes out clean, about 25 minutes.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 76,
                            DurationMin = 0,
                            Instruction = "Transfer the pans to wire racks. Let the cakes rest in their pans for about 2 minutes, then carefully flip them out onto the racks. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 77,
                            DurationMin = 0,
                            Instruction = " Turn them right side up on the racks and let them cool completely.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 78,
                            DurationMin = 0,
                            Instruction = "Roulade Pour the batter into the prepared baking sheet and spread it evenly to the corners with an offset spatula.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 79,
                            DurationMin = 0,
                            Instruction = "Bake the roulade until the cake is golden brown and springs back in the center and a cake tester comes out clean, about 16 minutes.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 80,
                            DurationMin = 0,
                            Instruction = "When the cake is in the oven, start worrying about how you�re going to cool it. Clear off a substantial section of your counter and spread out a clean, lint-free kitchen towel ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 81,
                            DurationMin = 0,
                            Instruction = "Sift a liberal amount of confectioners� sugar over the towel.",
                            IsDone = false
                        },
                        new
                        {
                            Id = 82,
                            DurationMin = 0,
                            Instruction = "When the cake is ready, run a knife around the edge of the pan. Invert onto the towel and remove the silicone baking mat or parchment. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 83,
                            DurationMin = 0,
                            Instruction = "Dust the top with additional confectioners� sugar and, beginning at a short end, roll the cake and towel into a tight log. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 84,
                            DurationMin = 0,
                            Instruction = "Transfer the cake to a wire rack and let it cool completely. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 85,
                            DurationMin = 0,
                            Instruction = "The cooled cakes can be used immediately or wrapped and refrigerated for up to 2 days. ",
                            IsDone = false
                        },
                        new
                        {
                            Id = 86,
                            DurationMin = 0,
                            Instruction = "Round layers can be frozen for up to 1 month\"",
                            IsDone = false
                        });
                });

            modelBuilder.Entity("ChefByStep.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 0,
                            Name = "Frieda",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 0,
                            Name = "Alberto",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 0,
                            Name = "Octaaf",
                            RoleId = 0
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 0,
                            Name = "Gert",
                            RoleId = 0
                        });
                });

            modelBuilder.Entity("RecipeStep", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("StepsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "StepsId");

                    b.HasIndex("StepsId");

                    b.ToTable("RecipeStep");
                });

            modelBuilder.Entity("RecipeUser", b =>
                {
                    b.Property<int>("CompletedById")
                        .HasColumnType("int");

                    b.Property<int>("CompletedRecipesId")
                        .HasColumnType("int");

                    b.HasKey("CompletedById", "CompletedRecipesId");

                    b.HasIndex("CompletedRecipesId");

                    b.ToTable("UserCompletedRecipes");
                });

            modelBuilder.Entity("RecipeUser1", b =>
                {
                    b.Property<int>("FavoriteRecipesId")
                        .HasColumnType("int");

                    b.Property<int>("FavouritedById")
                        .HasColumnType("int");

                    b.HasKey("FavoriteRecipesId", "FavouritedById");

                    b.HasIndex("FavouritedById");

                    b.ToTable("UserFavouriteRecipes");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.Recipe", b =>
                {
                    b.HasOne("ChefByStep.API.Entities.User", "CreatedBy")
                        .WithMany("CreatedRecipes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("ChefByStep.API.Entities.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefByStep.API.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.RecipeRating", b =>
                {
                    b.HasOne("ChefByStep.API.Entities.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChefByStep.API.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeStep", b =>
                {
                    b.HasOne("ChefByStep.API.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefByStep.API.Entities.Step", null)
                        .WithMany()
                        .HasForeignKey("StepsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeUser", b =>
                {
                    b.HasOne("ChefByStep.API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefByStep.API.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("CompletedRecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeUser1", b =>
                {
                    b.HasOne("ChefByStep.API.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("FavoriteRecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefByStep.API.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FavouritedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChefByStep.API.Entities.Ingredient", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ChefByStep.API.Entities.User", b =>
                {
                    b.Navigation("CreatedRecipes");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
